"""Write docs/coverage_table.tex from output/coverage.csv (LaTeX-escaped)."""
from __future__ import annotations

from pathlib import Path

import pandas as pd

HERE = Path(__file__).resolve().parent
COV = HERE.parent / "output" / "coverage.csv"
OUT = HERE / "coverage_table.tex"

REPL = (
    ("\\", r"\textbackslash{}"),
    ("&", r"\&"),
    ("%", r"\%"),
    ("$", r"\$"),
    ("#", r"\#"),
    ("_", r"\_"),
    ("{", r"\{"),
    ("}", r"\}"),
    ("~", r"\textasciitilde{}"),
    ("^", r"\textasciicircum{}"),
    ("Türkiye", r'T\"urkiye'),
    ("ü", r'\"u'),
    ("ö", r'\"o'),
    ("é", r"\'e"),
    ("á", r"\'a"),
    ("í", r"\'i"),
    ("ó", r"\'o"),
    ("–", "--"),
    ("—", "---"),
    ("’", "'"),
    ("‘", "'"),
)


def esc(s: object) -> str:
    t = "" if pd.isna(s) else str(s)
    for a, b in REPL:
        t = t.replace(a, b)
    return t


def emp_label(src: object) -> str:
    s = str(src)
    if "replaced with interpolated" in s:
        return "Q, patched"
    if "quarterly (official)" in s and "linear interpolation" not in s:
        return "Q official"
    if "linear interpolation" in s:
        return "A interpolated"
    return "other"


def main() -> None:
    cov = pd.read_csv(COV)
    body = []
    for r in cov.itertuples(index=False):
        body.append(
            f"{esc(r.country)} & {esc(r.country_name)} & {esc(r.gdp_sa)} & "
            f"{int(r.n)} & {esc(r.t0)} & {esc(r.t1)} & {emp_label(r.emp_source)} \\\\"
        )
    tex = r"""% Auto-generated by make_coverage_table.py from output/coverage.csv.
\begin{footnotesize}
\begin{longtable}{l>{\raggedright\arraybackslash}p{2.2in}cccll}
\caption{Country coverage of the constructed panel. Emp.\ is the
country-level employment source: official quarterly ILO (Q official);
official quarterly with isolated $4\times$ patches from interpolated
annual (Q, patched); or linearly interpolated official annual
(A interpolated). SA/NSA is the country-level GDP seasonal-adjustment
choice.}
\label{tab:coverage}\\
\toprule
ISO3 & Country & SA & $N$ & Start & End & Emp. \\
\midrule
\endfirsthead
\toprule
ISO3 & Country & SA & $N$ & Start & End & Emp. \\
\midrule
\endhead
\midrule
\multicolumn{7}{r}{\emph{Continued on next page}}\\
\endfoot
\bottomrule
\endlastfoot
"""
    tex += "\n".join(body) + "\n\\end{longtable}\n\\end{footnotesize}\n"
    OUT.write_text(tex, encoding="ascii")
    print(f"wrote {OUT}  {len(body)} rows")


if __name__ == "__main__":
    main()
